### ISSUE TITLE
Quality_Assessment fails to report the correct read length

### ISSUE THREAD

**Issue by Aerin13** [MorrellLAB/sequence_handling#36]
Quality_Assessment fails to report the correct read length in the quality summary file when using Illumina 1.5 encoding.

**Comment by fervet01** [comment]
What does this mean?..

Sent from my iPhone

On Mar 16, 2018, at 4:03 PM, Skylar Wyant <notifications@github.com> wrote:

Quality_Assessment fails to report the correct read length in the quality
summary file when using Illumina 1.5 encoding.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MorrellLAB/sequence_handling/issues/36>, or mute the
thread

**Comment by Aerin13** [comment]
Emily's Drosophila FASTQ files use a different quality encoding than our other FASTQ files, so it messes up the read length column in the Quality_Assessment summary table that's output by sequence_handling. It outputs a month and year instead of a length in base pairs. 

This shouldn't be anything that you should worry about for your samples. It's just a reminder for me to fix this issue next week when I have time.

**Comment by fervet01** [comment]
Ok. Thanks for the explanation.

Sent from my iPhone

On Mar 17, 2018, at 6:41 PM, Skylar Wyant <notifications@github.com> wrote:

Emily's Drosophila FASTQ files use a different quality encoding than our
other FASTQ files, so it messes up the read length column in the
Quality_Assessment summary table that's output by sequence_handling. It
outputs a month and year instead of a length in base pairs.

This shouldn't be anything that you should worry about for your samples.
It's just a reminder for me to fix this issue next week when I have time.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/MorrellLAB/sequence_handling/issues/36#issuecomment-373960990>,
or mute the thread
