### ISSUE TITLE
Options to Help With GATK HaplotypeCaller Making False Negative Errors

### ISSUE THREAD

**Issue by TomJKono** [MorrellLAB/sequence_handling#37]
My colleague has alerted me to an issue where HaplotypeCaller makes false negative errors on human samples. HaplotypeCaller makes some decisions on what it calls "active regions," and these may not include real variants, which causes some variant calls to be missed. This issue, and a related one about padding around active regions, were raised in this thread: https://github.com/broadinstitute/gatk/issues/3697.

She has generated BAM files using the GATK HaplotypeCaller active regions and compared them to the BAM files used for input: https://github.com/broadinstitute/gatk/issues/3697#issuecomment-399561285. The two BAM files shown are two samples from the same person. The intervals shown above each sample are the HaplotypeCaller active regions, which should be the same for each sample.

The solution seems to be to add `--dontTrimActiveRegions true` and `--forceActive` (`--dont-trim-active-regions true` for GATK 4.0, and `-forceActive` does not seem to exist in GATK 4.0) to the HaplotypeCaller command line to force every base to be considered an active region. This makes the runtimes very long, though, so we should recommend splitting by chromosome or some other region of interest.

**Comment by Aerin13** [comment]
Thanks for bringing this up. [This commit](https://github.com/MorrellLAB/sequence_handling/commit/eeeeadcde60fcf8357b5a1c91c893422df6fee99) adds two parameters to the Config file to allow the user to add `--dontTrimActiveRegions true` and `--forceActive` to GATK 3.8 HaplotypeCaller. I'm currently running some testing to look into adding options to split by chromosome or by user-defined regions.

**Comment by Aerin13** [comment]
From my own testing with 7 whole-genome soybean samples, adding both `--dontTrimActiveRegions true` and `--forceActive` increases the runtime substantially, following (old runtime)^1.26. Since HaplotypeCaller already takes a decent chunk of time even without those options, I was curious to see how many false negatives were picked up by adding those options to see if it was worth the runtime cost.

I ended up with some peculiar results. For my 7 samples, allowing GATK to determine the active regions in the default manner yielded 7.98 million SNPs (before any sort of filtering). When I added `--dontTrimActiveRegions true` and `--forceActive` and changed nothing else, those same 7 samples yielded only 7.82 million SNPs, but took approximately 5 times longer to run.
